// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://athrxtapdreclubxdlnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aHJ4dGFwZHJlY2x1YnhkbG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDA2MDAsImV4cCI6MjA1Nzg3NjYwMH0.iyA-v-ALSiZLMUZrwFdI6v9yk3oVt_Zq17PaFQ_470M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);